name: Run Python Script Every 2 Hours

on:
  schedule:
    - cron: '0 */2 * * *'  # Chạy mỗi 2 tiếng (00:00, 02:00, 04:00, v.v. UTC)
  workflow_dispatch:  # Cho phép chạy thủ công

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # Chỉ định phiên bản Python
          cache: 'pip'  # Tăng tốc bằng cách cache pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}  # Nếu API cần token
        run: python easychair.py

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "Update data from script" --allow-empty)
        continue-on-error: true  # Tiếp tục ngay cả khi commit thất bại

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
        continue-on-error: true  # Tiếp tục ngay cả khi push thất bại